/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binikomi.wc;

import picocli.CommandLine;

public class App {

  public static void main(String[] args) {
    final var appRunner = new AppRunner();
    final var commandLine = new CommandLine(appRunner);
    commandLine.execute(args);
  }
}
