/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binikomi.wc;

import java.nio.file.Path;
import java.util.List;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

@Command(mixinStandardHelpOptions = true)
class AppRunner implements Runnable {

  @Option(names = {"-c", "--bytes"})
  private boolean printBytes;

  @Option(names = {"-m", "--chars"})
  private boolean printChars;

  @Option(names = {"-w", "--words"})
  private boolean printWords;

  @Option(names = {"-l", "--lines"})
  private boolean printLines;

  @Parameters private List<Path> files;

  @Override
  public void run() {
    final var options = getOptions();
    System.out.println("Options: " + options);
    System.out.println("Files: " + files);
  }

  private Options getOptions() {
    if (printBytes || printChars || printWords || printLines) {
      return new OptionsBuilder()
          .printBytes(printBytes)
          .printChars(printChars)
          .printWords(printWords)
          .printLines(printLines)
          .build();
    }

    // when no options are provided, return default option.
    return Options.DEFAULT_OPTIONS;
  }
}
